name: beagleboneblack.sergiusens
vendor: Sergio Schvezov <sergiusens@gmail.com>
icon: meta/element14.png
version: 1.3
type: oem

immutable-config:
    - ubuntu-core/hostname*

config:
    ubuntu-core:
        hostname: ubuntu-rocks
        autopilot: true
        timezone: America/Cordoba

oem:
    branding:
        name:  Beagle Bone Black
        subname: by sergiusens

    software:
        built-in:
            - pastebinit.mvo
        preinstalled:
            - system-status.victor
    hardware:
        platform: am335x-boneblack
        architecture: armhf
        partition-layout: system-AB
        boot-assets:
            files:
                - path: uEnv.txt
            raw-files:
                - path: MLO
                  offset: 131072 # 128 * 1024
                - path: u-boot.img
                  offset: 393216 # 384 * 1024
